repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
        args:
        -   --fix=lf
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
    -   id: pretty-format-json
        args:
        -   --autofix
        -   --indent
        -   '4'
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.2.0
    hooks:
    -   id: pretty-format-yaml
        args:
        -   --autofix
        -   --indent
        -   '4'
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.10
    hooks:
    -   id: mdformat
        args:
        -   --end-of-line
        -   lf
        additional_dependencies:
        -   mdformat-gfm
        -   mdformat-black
-   repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
    -   id: yamllint
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.29.0
    hooks:
    -   id: markdownlint
-   repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
    -   id: beautysh
        types: [bash, shell]
        args:
        -   --indent-size
        -   '4'
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.1
    hooks:
    -   id: shellcheck
-   repo: https://github.com/Takishima/cmake-pre-commit-hooks
    rev: v1.5.0
    hooks:
    -   id: clang-format
        args:
        -   -i
    -   id: cppcheck
        args:
        -   --suppress=*:*moc_*
    -   id: clang-tidy
#include-what-you-use
    -   id: lizard
